blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#/blog/
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]{1})/$', views.DetailView.as_view(), name='detail'),
	#url(r'^(?P<pk>[0-9]+)/[a-z]/$', views.DetailView.as_view(), name='detail'),
	#/blog/2014
	url(r'^(?P<year>[0-9]{4})/$', views.YearView.as_view(), name='year'),
	#/blog/2014/05/
	url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.MonthView.as_view(month_format='%m'), name="month_numeric"),
	#/blog/2014/aug
	url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/$', views.MonthView.as_view(), name="month"),
	url(r'^(?P<slug>[-\w]+)/$', views.DetailTestView.as_view(), name='detailtest'),
	#/blog/2014/05/26
	#url(r'^(?P<year>[0-9]{4}/(?P<month>[0-9]{2}/(?P<day>[0-9]{2}/$', views.article_detail), 
]

mysite/urls.py
from django.conf.urls     import include, url
from django.contrib       import admin
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',  include('blog.urls', namespace="blog")),
    url(r'^$',      TemplateView.as_view(template_name="index.html")),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#/polls/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#/polls/5
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	#/polls/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	#/polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify

class Post(models.Model):
	post_title = models.CharField(max_length=100, unique=True)
	post_content = models.TextField()
	pub_date = models.DateTimeField('date published')
	post_slug = models.SlugField(null=True, blank=True, unique=True)
	
	def __unicode__(self):
		return self.post_title
		
	def get_year(self):
		return self.pub_date.year
		
	def get_month(self):
		return self.pub_date.month
		
	def get_day(self):
		return self.pub_date.day
		
	def get_previous(self):
		return self.id - 1
		
	def get_next(self):
		return self.id + 1
		
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		
	def save(self, *args, **kwargs):
		if not self.id:
			if not self.post_slug:
				self.post_slug = slugify(self.post_title)
			
		super(Post, self).save(*args, **kwargs)
		
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	



# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __unicode__(self):
		return self.question_text
		
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	
	
class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text

blog/views.py
from django.shortcuts           import get_object_or_404, render
from django.http                import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers   import reverse
from django.views               import generic
from django.utils               import timezone
from django.core.paginator      import Paginator, EmptyPage
from django.views.generic.dates import YearArchiveView
from django.views.generic.dates import MonthArchiveView

from .models import Post
# Create your views here.

class IndexView(generic.ListView):
	model = Post
	date_field = "pub_date"
	template_name = 'blog/index.html'
	context_object_name = 'latest_post_list'
	
	def get_queryset(self):
		return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
		
class DetailView(generic.DetailView):
	model = Post
	template_name = 'blog/detail.html'
	
	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Post.objects.filter(pub_date__lte=timezone.now())
		
class DetailTestView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	slug_field = 'post_slug'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Post.objects.filter(pub_date__lte=timezone.now())

class YearView(YearArchiveView):
	template_name ='blog/year.html'
	queryset = Post.objects.all()
	date_field = "pub_date"
	make_object_list = True
	allow_future = True
	
class MonthView(MonthArchiveView):
	template_name = 'blog/month.html'
	queryset = Post.objects.all()
	date_field = "pub_date"
	allow_future = True


# 	model = Post
# 	template_name = 'blog/year.html'
# 	context_object_name = 'year_list'
# 	
# 	def get_queryset(self):
# 		return Post.objects.filter(pub_date__year=year).order_by('pub_date')
	
#class DetailView(generic.DetailView):
#	model = Post

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		"""Return the last five published questions (not including those set to be published in the future)."""
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
		
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())
	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'
	
def vote(request, question_id):
	p = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redirect, redisplays the question voiting form
		return render(request, 'polls/detail.html', {
			'question': p,
			'error_message': "You didn't select a choice.", 
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		
		# Always return an HttpResponseRedirect after successfully dealing with POST data
		# This prevents data from being posted twice if the user hits the Back button.
		
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))




# Create your views here.
# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	context = {'latest_question_list': latest_question_list}
# 	return render(request, 'polls/index.html', context)
# 	
# def detail(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/detail.html', {'question': question})
# 	
# def results(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/results.html', {'question': question})
# 	
# def vote(request, question_id):
# 	p = get_object_or_404(Question, pk=question_id)
# 	try:
# 		selected_choice = p.choice_set.get(pk=request.POST['choice'])
# 	except (KeyError, Choice.DoesNotExist):
# 		# Redirect, redisplays the question voiting form
# 		return render(request, 'polls/detail.html', {
# 			'question': p,
# 			'error_message': "You didn't select a choice.", 
# 		})
# 	else:
# 		selected_choice.votes += 1
# 		selected_choice.save()
# 		
# 		# Always return an HttpResponseRedirect after successfully dealing with POST data
# 		# This prevents data from being posted twice if the user hits the Back button.
# 		
# 		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

blog/templates/blog/buttons.html
<div id="themeButtons">
	{% load staticfiles %}
	<br />
	<br />
	<button type="button" id="darkTheme">Dark theme</button>
	<button type="button" id="lightTheme">Light theme</button>
	<script src="{% static 'blog/styleswitch.js' %}"> </script>
</div>

blog/templates/blog/detail.html
<!Doctype html>
<html>
	{% include 'blog/head.html' %}
	<header>
	<div class="logo container">This is a logo</div>
		<div class="nav-div container">
			<nav>
				<a class="link" href="/">Home</a>
				<a class="link" href="/blog">Blog</a>
				<a class="link" href="{% url 'blog:detail' post.get_previous %}">Previous</a>
				<a class="link" href="{% url 'blog:detail' post.get_next %}">Next</a>
			</nav>
			<hr/>
		</div>
</header>
	<body>
		<div class="container">
			<h1 class="postTitle">{{ post.post_title }}</h1>
			
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			
			<div id="postContent">
				{{ post.post_content|safe }}
			</div>
			{% include 'blog/buttons.html' %}
		</div>
	</body>
</html>

blog/templates/blog/head.html
<head>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'blog/prismdark.css' %}"  title="dark"  />
	<link rel="stylesheet" type="text/css" href="{% static 'blog/prismlight.css' %}" title="light" disabled />
	<script src="{% static 'blog/prism.js' %}"></script>
</head>

blog/templates/blog/index.html
<!Doctype html>
<html>
	{% include 'blog/head.html' %}
	{% if latest_post_list %}
	{% include 'blog/nav.html' %}
	<body>
		<div class="container">
			<h1>Hey, this is a test page for my blog app</h1>
			{% for post in latest_post_list %}
			<h1 class="postTitle">{{ post.post_title }}</h1>
			<div class="postContent">
				"{{ post.post_content|striptags|slice:":100" }} . . ." <a href="{% url 'blog:detailtest' post.post_slug %}">Read more →</a>
					<!--- {{ post.post_content|safe }} for actual content -->
			</div>
			{% endfor %}
			{% include 'blog/buttons.html' %}
		</div>
	</body>
</html>
	{% else %}
	<p>No blog posts are available.</p>
	{% endif %}

blog/templates/blog/month.html
<!Doctype html>
<html>
	<head>
{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
	</head>
<body>
	<div class="container">
		<h1>Hey, this is a test page for my month archive</h1>
		<ul>
			{% for post in object_list %}
				<li>{{ post.pub_date|date:"F j, Y" }}: <a href="{% url 'blog:detailtest' post.post_slug %}">{{ post.post_title }}</a></li>
			{% endfor %}
		</ul>
		<p>
			{% if previous_month %}
				Previous Month: {{ previous_month|date:"F Y" }}
			{% endif %}
		</p>
		<p>	
			{% if next_month %}
				Next Month: {{ next_month|date:"F Y" }}
			{% endif %}
		</p>
	</div>
</body>

blog/templates/blog/nav.html
<header>
	<div class="logo container">This is a logo</div>
		<div class="nav-div container">
			<nav>
				<a class="link" href="/">Home</a>
				<a class="link" href="/blog">Blog</a>
				<a class="link" href="/duper/">Duper</a>
			</nav>
			<hr/>
		</div>
</header>

blog/templates/blog/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

blog/templates/blog/year.html
<!Doctype html>
<html>
	{% include 'blog/head.html' %}
	{% include 'blog/nav.html' %}
	<body>
	<div class="container">
		<h1>Hey, this is a test page for my year archive</h1>
		<ul>
		    {% for date in date_list %}
		        <li>{{ date|date }}</li>
		    {% endfor %}
		</ul>	
		<div>
		    <h1>All Posts for {{ year|date:"Y" }}</h1>
		    {% for post in object_list %}
		        <p>
		            <a href="{% url 'blog:detailtest' post.post_slug %}">{{ post.post_title }}</a> - {{ post.pub_date|date:"F j, Y" }}
		        </p>
		    {% endfor %}
		</div>
	</div>
</body>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	<br />
{% endfor %}

<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<!Doctype html>
<html>
	<head>
{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
	</head>
{% if latest_question_list %}
<body>
	<div class="container">
		<h1>Hey, this is a test page for my polls app</h1>
		<ul>
			{% for question in latest_question_list %}
				<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
			{% endfor %}
		</ul>
	</div>
</body>
	{% else %}
	<p>No polls are available.</p>
	{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/index.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'blog/homepage.css' %}">
	</head>
	<body>
		<header>
			<div class="logo container">This is a logo</div>
			<div class="nav-div container">
				<nav>
					<a class="link" href="/">Home</a>
					<a class="link" href="/blog/">Blog</a>
					<a class="link" href="/duper/">Duper</a>
				</nav>
				<hr/>
			</div>
		</header>
		<div class="main container">
			<h1>Hello World!</h1>
		</div>
	</body>
</html>